apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: common-nodejs-parent-2-4-x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sdouglas1-tenant/operator-test-1-2-x/common-nodejs-parent-2-4-x@sha256:087a73f9eca1b6c1b06b05e93bcf879798bdfecc159ada8960871b1706c59efa
        name: container-image
        resources: {}
status: {}
