apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent-2-4-x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent-2-4-x
    app.kubernetes.io/part-of: operator-test-1-2-x
  name: common-nodejs-parent-2-4-hof7
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: common-nodejs-parent-2-4-x
    weight: 100
status: {}
