apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent
    app.kubernetes.io/part-of: operator-test-1-2-x
  name: common-nodejs-parent
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: common-nodejs-parent
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: common-nodejs-parent
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sdouglas1-tenant/operator-test-1-2-x/common-nodejs-parent@sha256:0fd2c6cdd44207aadac45cd2df521b15f018df465fcddb27f687293cf0032227
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
