apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: common-nodejs-parent-2-4-x
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: common-nodejs-parent-2-4-x
    app.kubernetes.io/part-of: operator-test-1-2-x
  name: common-nodejs-parent-2-4-x
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: common-nodejs-parent-2-4-x
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: common-nodejs-parent-2-4-x
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/sdouglas1-tenant/operator-test-1-2-x/common-nodejs-parent-2-4-x@sha256:75b28cbe2fca2f1e2a360482ff30515c8ab4e49c2423530a3cf7e13eb2741d3a
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
